[versions]
agp = "8.7.3"
converterScalars = "2.11.0"
dexter = "6.2.3"
glide = "4.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.3"
constraintlayout = "2.2.0"
photoview = "2.3.0"
retrofit = "2.11.0"
signaturePad = "1.3.1"
signatureView = "0.1.2"
whynotimagecarousel = "2.1.0"

[libraries]
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
dexter = { module = "com.karumi:dexter", version.ref = "dexter" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
photoview = { module = "com.github.chrisbanes:PhotoView", version.ref = "photoview" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit2-converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "converterScalars" }
signature-pad = { module = "com.github.gcacace:signature-pad", version.ref = "signaturePad" }
signature-view = { module = "se.warting.signature:signature-view", version.ref = "signatureView" }
whynotimagecarousel = { module = "org.imaginativeworld.whynotimagecarousel:whynotimagecarousel", version.ref = "whynotimagecarousel" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

